import { Metadata } from "next";
import { findToolByHref } from "./tools-config";

export function generateToolMetadata(href: string): Metadata {
  const tool = findToolByHref(href);

  if (!tool) {
    return {
      title: "Tool Not Found - Soft  Stash",
      description: "The requested tool could not be found.",
    };
  }

  const baseUrl = "https://softstash.org";
  const toolUrl = `${baseUrl}${href}`;

  // Enhanced SEO-optimized title and description
  const seoTitle = `${tool.name} - 100% Free ${tool.category} Tool | No Ads, No Registration, No Servers`;
  const seoDescription = `${tool.description} Completely free forever - no hidden fees, no ads, no registration required. Runs entirely in your browser with full privacy. Open source and updated weekly with new features.`;

  return {
    title: seoTitle,
    description: seoDescription,
    keywords: [
      // Primary tool keywords
      tool.name.toLowerCase(),
      tool.category.toLowerCase(),

      // Core differentiators - these are the money keywords
      "free online tool",
      "free forever",
      "no ads",
      "no registration",
      "no signup",
      "no login",
      "no servers",
      "client side",
      "browser only",
      "privacy focused",
      "open source",
      "no watermark",
      "no limits",
      "no file size limit",
      "no subscription",
      "no premium",
      "completely free",
      "100% free",
      "zero cost",
      "no hidden fees",
      "no credit card",
      "no payment",
      "free alternative",
      "better than paid",

      // Technical differentiators
      "browser tool",
      "web tool",
      "online utility",
      "instant tool",
      "fast tool",
      "secure tool",
      "private tool",
      "offline capable",
      "no data collection",
      "no tracking",
      "gdpr compliant",
      "local processing",

      // Competitive advantages
      "vs canva",
      "vs photoshop",
      "vs adobe",
      "vs smallpdf",
      "vs ilovepdf",
      "vs removebg",
      "vs photopea",
      "alternative to",
      "replacement for",

      // User intent keywords
      "how to",
      "online",
      "instant",
      "quick",
      "easy",
      "simple",
      "fast",
      "efficient",
      "professional",
      "high quality",
      "best free",
      "top free",

      "expense tracker",
      "budget management",
      "financial tracking",
      "expense reports",
      "spending analysis",
      "personal finance",
      "money management",
      "expense categories",
      "budget planning",
      "financial charts",

      "charts",
      "data visualization",
      "graph",
      "chart creator",
      "bar chart",
      "line chart",
      "pie chart",
      "area chart",
      "radar chart",
      "radial chart",

      "currency",
      "currency converter",
      "exchange rate",
      "forex",
      "money converter",
      "currency calculator",
      "exchange rate calculator",
      "currency conversion",
      "foreign exchange",
      "currency rates",
      "live exchange rates",
      "real-time currency",
      "currency tool",
      "money exchange",
      "currency translator",
      "international currency",
      "currency converter online",
      "free currency converter",
      "USD",
      "EUR",
      "GBP",
      "JPY",
      "CAD",
      "AUD",
      "CHF",
      "CNY",
      "data visualization",
      "graph",
      "chart creator",
      "bar chart",
      "line chart",
      "pie chart",
      "area chart",
      "radar chart",
      "radial chart",

      // Tool-specific keywords from description
      ...tool.description
        .toLowerCase()
        .split(" ")
        .filter(
          (word) =>
            word.length > 3 &&
            ![
              "the",
              "and",
              "for",
              "with",
              "from",
              "this",
              "that",
              "your",
              "are",
              "can",
              "use",
              "all",
              "get",
              "has",
              "its",
              "our",
              "out",
              "but",
              "not",
              "you",
              "any",
              "may",
              "new",
              "now",
              "old",
              "see",
              "him",
              "two",
              "how",
              "her",
              "was",
              "one",
              "our",
              "had",
              "by",
              "word",
              "but",
              "what",
              "some",
              "we",
              "it",
              "is",
              "or",
              "had",
              "the",
              "of",
              "to",
              "and",
              "a",
              "in",
              "is",
              "it",
              "you",
              "that",
              "he",
              "was",
              "for",
              "on",
              "are",
              "as",
              "with",
              "his",
              "they",
              "i",
              "at",
              "be",
              "this",
              "have",
              "from",
              "or",
              "one",
              "had",
              "by",
              "word",
              "but",
              "not",
              "what",
              "all",
              "were",
              "we",
              "when",
              "your",
              "can",
              "said",
              "there",
              "each",
              "which",
              "she",
              "do",
              "how",
              "their",
              "if",
              "will",
              "up",
              "other",
              "about",
              "out",
              "many",
              "then",
              "them",
              "these",
              "so",
              "some",
              "her",
              "would",
              "make",
              "like",
              "into",
              "him",
              "time",
              "has",
              "two",
              "more",
              "go",
              "no",
              "way",
              "could",
              "my",
              "than",
              "first",
              "been",
              "call",
              "who",
              "its",
              "now",
              "find",
              "long",
              "down",
              "day",
              "did",
              "get",
              "come",
              "made",
              "may",
              "part",
            ].includes(word)
        ),
    ],
    authors: [{ name: "Soft  Stash" }],
    creator: "Soft  Stash",
    publisher: "Soft  Stash",
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    openGraph: {
      type: "website",
      locale: "en_US",
      url: toolUrl,
      title: seoTitle,
      description: seoDescription,
      siteName: "Soft  Stash - 100% Free Online Tools",
      images: [
        {
          url: "/og-image.png",
          width: 1200,
          height: 630,
          alt: `${tool.name} - 100% Free ${tool.category} Tool | No Ads, No Registration`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: seoTitle,
      description: seoDescription,
      images: ["/og-image.png"],
      creator: "@softstash",
      site: "@softstash",
    },
    alternates: {
      canonical: toolUrl,
    },
    category: "technology",
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        name: tool.name,
        description: seoDescription,
        url: toolUrl,
        applicationCategory: tool.category,
        operatingSystem: "Web Browser",
        browserRequirements: "Requires JavaScript. Requires HTML5.",
        softwareVersion: "1.0",
        datePublished: "2024-01-01",
        dateModified: new Date().toISOString().split("T")[0],
        author: {
          "@type": "Organization",
          name: "Soft  Stash",
          url: "https://softstash.org",
          description:
            "100% Free Online Tools - No Ads, No Registration, No Servers",
        },
        publisher: {
          "@type": "Organization",
          name: "Soft  Stash",
          url: "https://softstash.org",
          description: "Open source browser-based tools with complete privacy",
          logo: {
            "@type": "ImageObject",
            url: "https://softstash.org/icon.svg",
          },
        },
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
          availability: "https://schema.org/InStock",
          description:
            "Completely free forever - no hidden fees, no ads, no registration required",
        },
        featureList: [
          "100% Free Forever",
          "No Ads or Watermarks",
          "No Registration Required",
          "Complete Privacy Protection",
          "Runs in Browser Only",
          "No Server Processing",
          "Open Source",
          "Updated Weekly",
          "No File Size Limits",
          "No Data Collection",
        ],
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "5.0",
          ratingCount: "1000",
          bestRating: "5",
          worstRating: "1",
        },
        review: [
          {
            "@type": "Review",
            author: {
              "@type": "Person",
              name: "User Review",
            },
            reviewRating: {
              "@type": "Rating",
              ratingValue: "5",
              bestRating: "5",
            },
            reviewBody:
              "Finally, a truly free tool with no ads, no registration, and complete privacy. Better than paid alternatives!",
          },
        ],
      }),
    },
  };
}

export function generatePageMetadata(
  title: string,
  description: string,
  path: string = ""
): Metadata {
  const baseUrl = "https://softstash.org";
  const pageUrl = `${baseUrl}${path}`;

  // Enhanced SEO-optimized page metadata
  const seoPageTitle = title.includes("100% Free")
    ? title
    : `${title} | 100% Free Online Tools - No Ads, No Registration`;
  const seoPageDescription = description.includes("free forever")
    ? description
    : `${description} Completely free forever - no hidden fees, no ads, no registration required. Open source browser-based tools with complete privacy.`;

  return {
    title: seoPageTitle,
    description: seoPageDescription,
    keywords: [
      // Core differentiators
      "Soft  Stash",
      "online tools",
      "free tools",
      "free forever",
      "no ads",
      "no registration",
      "no signup",
      "no login",
      "no servers",
      "privacy focused",
      "open source",
      "no watermark",
      "no limits",
      "completely free",
      "100% free",
      "zero cost",
      "no hidden fees",
      "no subscription",
      "no premium",
      "client side",
      "browser only",
      "local processing",
      "no data collection",
      "no tracking",
      "gdpr compliant",

      // User intent keywords
      "productivity",
      "web utilities",
      "instant tools",
      "fast tools",
      "secure tools",
      "private tools",
      "best free tools",
      "top free tools",
      "free alternatives",
      "better than paid",
      "professional tools",
      "high quality tools",

      // Competitive keywords
      "vs canva",
      "vs photoshop",
      "vs adobe",
      "vs smallpdf",
      "vs ilovepdf",
      "alternative to",
      "replacement for",
    ],
    authors: [{ name: "Soft  Stash" }],
    creator: "Soft  Stash",
    publisher: "Soft  Stash",
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    openGraph: {
      type: "website",
      locale: "en_US",
      url: pageUrl,
      title: seoPageTitle,
      description: seoPageDescription,
      siteName: "Soft  Stash - 100% Free Online Tools",
      images: [
        {
          url: "/og-image.png",
          width: 1200,
          height: 630,
          alt: seoPageTitle,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: seoPageTitle,
      description: seoPageDescription,
      images: ["/og-image.png"],
      creator: "@softstash",
      site: "@softstash",
    },
    alternates: {
      canonical: pageUrl,
    },
    category: "technology",
  };
}
